# Generated by Django 2.2.3 on 2019-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todoitem_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
