# Generated by Django 2.2.3 on 2019-07-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20190726_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Yapılacaklar'),
        ),
    ]
